export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'

export const CART_SAVE_ADDRESS = 'CART_SAVE_ADDRESS'

export const CART_SET_METHOD = 'CART_SET_METHOD'

export const BADGE_GET_POSITION = 'BADGE_GET_POSITION'

export const CALL_TO_BOUNCE = 'CALL_TO_BOUNCE'
export const CALL_BOUNCE_RESET = 'CALL_BOUNCE_RESET'
